# Generated by Django 4.2.2 on 2023-06-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('preamble', models.CharField(blank=True, max_length=1024, null=True, verbose_name='preamble')),
                ('body', models.TextField(verbose_name='body')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date of creating')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date of editing')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
