# Generated by Django 4.2.2 on 2023-06-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('preamble', models.CharField(max_length=1024, verbose_name='Preamble')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ('-created',),
            },
        ),
    ]
